export const FETCHING_USERS_DATA = 'FETCHING_USERS_DATA';
export const FETCHING_USERS_DATA_SUCCESS = 'FETCHING_USERS_DATA_SUCCESS';
export const FETCHING_USERS_DATA_FAIL = 'FETCHING_USERS_DATA_FAIL';

export const SET_USER_DATA = 'SET_USER_DATA';

export const FETCHING_ALBUMS_DATA = 'FETCHING_ALBUMS_DATA';
export const FETCHING_ALBUMS_DATA_SUCCESS = 'FETCHING_ALBUMS_DATA_SUCCESS';
export const FETCHING_ALBUMS_DATA_FAIL = 'FETCHING_ALBUMS_DATA_FAIL';

export const SET_ALBUM_DATA = 'SET_ALBUM_DATA';

export const FETCHING_POSTS_DATA = 'FETCHING_POSTS_DATA';
export const FETCHING_POSTS_DATA_SUCCESS = 'FETCHING_POSTS_DATA_SUCCESS';
export const FETCHING_POSTS_DATA_FAIL = 'FETCHING_POSTS_DATA_FAIL';

export const SET_POST_DATA = 'SET_POST_DATA';

export const FETCHING_TODOS_DATA = 'FETCHING_TODOS_DATA';
export const FETCHING_TODOS_DATA_SUCCESS = 'FETCHING_TODOS_DATA_SUCCESS';
export const FETCHING_TODOS_DATA_FAIL = 'FETCHING_TODOS_DATA_FAIL';

export const SET_TODO_DATA = 'SET_TODO_DATA';

export const FETCHING_PHOTOS_DATA = 'FETCHING_PHOTOS_DATA';
export const FETCHING_PHOTOS_DATA_SUCCESS = 'FETCHING_PHOTOS_DATA_SUCCESS';
export const FETCHING_PHOTOS_DATA_FAIL = 'FETCHING_PHOTOS_DATA_FAIL';

export const FETCHING_COMMENTS_DATA = 'FETCHING_COMMENTS_DATA';
export const FETCHING_COMMENTS_DATA_SUCCESS = 'FETCHING_COMMENTS_DATA_SUCCESS';
export const FETCHING_COMMENTS_DATA_FAIL = 'FETCHING_COMMENTS_DATA_FAIL';
